# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160623_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
