# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160623_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsMaxLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxlevel', models.IntegerField(default=0, editable=False, null=True, verbose_name='Максимальный уровень вложенности для ветки')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='level',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Уровень вложенности'),
        ),
        migrations.AddField(
            model_name='posts',
            name='master_id',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Номер корня ветки сообщений'),
        ),
        migrations.AddField(
            model_name='postsmaxlevel',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts', verbose_name='Номер корня'),
        ),
    ]
