# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160624_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmaxlevel',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts', unique=True, verbose_name='Номер корня'),
        ),
    ]
