# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160624_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmaxlevel',
            name='master',
        ),
        migrations.AddField(
            model_name='posts',
            name='coments_count',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='количество комментариев'),
        ),
        migrations.DeleteModel(
            name='PostsMaxLevel',
        ),
    ]
