# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='posts',
            name='author_link',
            field=models.URLField(blank=True, null=True, verbose_name='Страничка автора в соцсетях'),
        ),
        migrations.AddField(
            model_name='posts',
            name='author_pic',
            field=models.URLField(blank=True, null=True, verbose_name='Страничка автора в соцсетях'),
        ),
    ]
